config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'users/setup_notice', to: "users#setup_notice", as: "setup_notice"
  get 'contacts/setup', to: "contacts#setup", as: "contacts_setup"

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  resources :contacts

  get 'dashboard' => 'dashboard#index'

  get 'dashboard/index'

  post 'responses/add'

  get 'pebble_settings/:pebble_token' => "users#connect_pebble", as: 'connect_pebble_sign_in'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts
  has_many :responses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    if params[:user][:pebble_token]
      if URI.parse(request.referer).path == connect_pebble_sign_in_path(params[:user][:pebble_token])
        URI.parse(request.referer).path
      end
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.where(user: current_user).all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def setup
    @contact = Contact.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :user_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @q1 = Response.where(kind: "1").order(:datetime)
    @q2 = Response.where(kind: "2").order(:datetime)

    if @q1.count < 3 || @q2.count < 3
      @insufficient = true
    end

    @answers1 = []
    @q1.each do |response|
      @answers1 << response.level
    end

    @dates1 = []
    @q1.each do |response |
        @dates1 << response.datetime.to_formatted_s(:db)
    end

    @answers2 = []
    @q2.each do |response|
      @answers2 << response.level
    end

    @yes = 0.0
    @no = 0.0
    @q2.each do |response|
      if response.level == 3
        @yes = @yes + 1.0
      elsif response.level == 1
        @no = @no + 1.0
      end
    end
    @yes = @yes/ (@yes + @no)
    @no = 1 - @yes
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    setup_notice_path
  end
end

app/controllers/responses_controller.rb
require 'contact_mailer'
class ResponsesController < ApplicationController
  protect_from_forgery with: :null_session

  def add
    # TODO: Authentication logic (is the pebble ID registered here?)

    response = Response.new(response_params)
    # response.user = User.find(response_params[:response][:user_id])
    response.datetime = DateTime.now
    # debug
    puts params
    puts response_params
    puts response

    current_user = User.find(response_params[:user_id])

    stress_mean = Response.where(kind: "1", user_id: current_user).pluck(:level).last(5).sum / 5.0
    happiness_mean = Response.where(kind: "2",user: current_user).pluck(:level).last(5).sum / 5.0
    threshold = 1.5

    if response.save
      if stress_mean > threshold && happiness_mean < threshold
        puts "Sending an e-mail triggered!"
        ContactMailer.depressing_email(current_user, current_user.contacts.sample).deliver
      else
        puts "Sending an e-mail not triggered! Stress mean #{stress_mean}, happiness #{happiness_mean}"
      end
      render status: 200, text: "Success (response saved)"
    else
      render status: 500, text: "Failure to save response"
    end
  end

  private
    def response_params
      params.require(:response).permit(:kind, :level, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: :connect_pebble


  def after_sign_up_path_for(resource_or_scope)
    setup_notice_path
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def connect_pebble
    if params[:pebble_token]
      @token = params[:pebble_token]
    end

    if params[:user]
      @token = params[:user][:pebble_token]
    end

    if user_signed_in?
      current_user.pebble_token = @token
      current_user.save
      render 'pebble_success', layout: 'minimal'
    else
      render layout: 'minimal'
    end
  end

  def setup_notice
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :user_id, as: :hidden, value: current_user.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.user %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/setup.html.erb
<h2>Add People Who Care</h2>
<p>People love you and care about you. They will appreciate the opportunity to help. Talk to them - and if they want to step in, put their name and e-mail here. We will let them know when you need them.</p>
<%= image_tag("wm4mcontact.png", :alt => "logo") %>
<p>
  Begin with a single person. Your best friend, your therapist, or maybe your mom. They will love to help you.
</p>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @contact.user %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/dashboard/index.html.erb
<div class="header">
<h1 class="text-center">YOUR HAPPINESS REPORT</h1>
<% if @insufficient %>
<p>
  ...will be available here when more of your responses are available! Make sure you <%= link_to "set up your Pebble", setup_notice_path %> and <%= link_to "include your friends and supporters", contacts_setup_path %>!
</p>
<% end %>
</div>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "/dashboard" %>
<% end %>

<% content_for :extra_javascripts do %>
<%= javascript_include_tag "dashboard.js" %>
<% end %>

<link href='http://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>
 <style>
     h1 {
      font-family: 'Quicksand';
     }
</style>
<% unless @insufficient %>
<div id="srs" data-lat="<%= @q2.to_a %>"> </div>
<div id="foo" data-lat="<%= @answers1 %>"> </div>
<div id="datetime1" data-lat="<%= @dates1 %>"> </div>
<div id="happysum" data-lat="<%= @yes %>"> </div>
<div id="sadsum" data-lat="<%= @no %>"> </div>
<div class="charts--container">
  <ul>
    <li class="chart">
      <h3 class="chart--subHeadline">HAPPINESS</h3>
      <h2 class="chart--headline">Happiness Percentage</h2>
      <div id="pieChart">
        <svg id="pieChartSVG">
          <defs>
            <filter id='pieChartInsetShadow'>
              <feOffset dx='0' dy='0'/>
              <feGaussianBlur stdDeviation='3' result='offset-blur' />
              <feComposite operator='out' in='SourceGraphic' in2='offset-blur' result='inverse' />
              <feFlood flood-color='black' flood-opacity='1' result='color' />
              <feComposite operator='in' in='color' in2='inverse' result='shadow' />
              <feComposite operator='over' in='shadow' in2='SourceGraphic' />
            </filter>
            <filter id="pieChartDropShadow">
              <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur" />
              <feOffset in="blur" dx="0" dy="3" result="offsetBlur" />
              <feMerge>
                <feMergeNode />
                <feMergeNode in="SourceGraphic" />
              </feMerge>
            </filter>
          </defs>
        </svg>
      </div>
    </li>
    <li class="chart">
      <h3 class="chart--subHeadline">STRESS</h3>
      <h2 class="chart--headline">Stress History</h2>
      <div id="lineChart">
        <svg id="lineChartSVG" class="lineChart--svg">
          <defs>
            <linearGradient id="lineChart--gradientBackgroundArea" x1="0" x2="0" y1="0" y2="1">
              <stop class="lineChart--gradientBackgroundArea--top" offset="0%" />
              <stop class="lineChart--gradientBackgroundArea--bottom" offset="100%" />
            </linearGradient>
          </defs>
        </svg>
      </div>
    </li>
  </ul>
</div>
<% end %>
<script type="text/javascript">
</script>
<%= yield :extra_javascripts %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to 'Dashboard', dashboard_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

  <li><%= link_to 'Contacts', contacts_path%></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Watch me for me!" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Watch me for me!" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/minimal.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Watch me for me!" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Watch me for me!" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/connect_pebble.html.erb
<div style="margin-top: 1em;">
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <p><%= f.label "Your e-mail:" %>
  <%= f.text_field :email %></p>
  <p><%= f.label "Password:" %>
  <%= f.password_field :password %></p>
  <%= f.hidden_field :pebble_token, value: @token %>
  <p><%= f.submit 'Sign in' %></p>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/pebble_success.html.erb
<h4>Your Pebble has been successfully linked to your account!</h4>
<p><strong>Please, click 'Save' to confirm the connection.</strong></p>

<form>
  <button id="saveBtn">Save</button>
</form>

<script>
function saveOptions() {
	var options = {
	  'confirmed': 1,
	}
	return options;
}

$().ready(function() {
	$("#saveBtn").on("touchend",function() {
	  console.log("Submitted after success");

	  var location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(saveOptions()));
	  console.log("Warping to: " + location);
	  console.log(location);
	  document.location = location;
	});
});
</script>

app/views/users/setup_notice.html.erb
<style>
.button {
  -webkit-border-radius: 7;
  -moz-border-radius: 7;
  border-radius: 7px;
  font-family: Arial;
  color: #ffffff;
  font-size: 24px;
  background: #e95265;
  padding: 10px 20px 10px 20px;
  text-decoration: none;
}

.button:hover {
  background: #2fbdaa;
  color: #ffffff;
  text-decoration: none;
}

</style>

<h2>You're almost there!</h2>
<p>In order to take full advantage of WatchMe4Me, go download our Pebble app and follow the instructions there.</p>


<%= image_tag("wm4mpebble.gif", :alt => "logo") %>
<p><%= link_to "Continue to Contacts Setup", contacts_setup_path, class: "button" %></p>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="jumbotron">
 <style>
     h1 {
      font-family: 'Quicksand';
      font-weight: 700;
      text-align: center;
     }
.button {
  -webkit-border-radius: 7;
  -moz-border-radius: 7;
  border-radius: 7px;
  font-family: Arial;
  color: #ffffff;
  font-size: 36px;
  background: #e95265;
  padding: 10px 20px 10px 20px;
  text-decoration: none;
}

.button:hover {
  background: #2fbdaa;
  color: #ffffff;
  text-decoration: none;
}


</style>

  <h1>Watch Me For Me</h1>
  <%= image_tag("wm4m.png", :alt => "logo") %>

  <p style = "text-align: center">
    Yet another proof that Pebbles make everything better: We help you keep tabs on your own mind.
  </p>
  <br>
  <p style = "text-align: center">
    <%= link_to 'Sign up today!', new_user_registration_path, class: 'button' %>

  </p>
</div>

<link href='http://fonts.googleapis.com/css?family=Quicksand:300,400' rel='stylesheet' type='text/css'>

<div class="row">
  <div class="col-md-4">
    <h2>Your Mind, Quantified</h2>
    <p>You want to track your moods the same way you track your movement and heartrate? <strong>We have just the tool for you</strong>, using established methodology from happiness research.</p>
  </div>
  <div class="col-md-4">
    <h2>Depressed?</h2>
    <p>
      <strong>We can help you reach out to the help you need</strong> - doctor, friends, family - when you're too sad to ask them yourself.
    </p>
  </div>
  <div class="col-md-4">
    <h2>Therapist?</h2>
    <p>
      We can help you <strong>take better care of your patients</strong>, allowing you to keep track of their state without requiring their ongoing initiative.
    </p>
  </div>
</div>